Repository Quadriphobs1/stopwatch, pull requests merged in 2019-10, with the labels that each got.

#3 CI/Coverage setup
  .circleci/config.yml
  README.md
  package.json
  src/serviceWorker.ts
Labels: enhancement

#11 integrated github workflows
  .github/workflows/config.yml
Labels: good first issue, hacktoberfest

#12 Refactor Github Actions
  .circleci/config.yml
  .github/auto_assign.yml
  .github/main.workflow
  .github/pr-labeler.yml
  .github/workflows/config.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/size-label.yml
  package.json
Labels: size/L
